export const colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#fff",
  COLOR_DARK: "#000",
  COLOR_DARK_ALT: "#262626",
};

export const recipeList = [
  {
    id: "01",
    name: "Tuna Tartare",
    image: require("../assets/images/download(1).jpg"),
    rating: "4.2",
    ingradients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "420 cal",
    description: [
      "A refreshing and light dish perfect for seafood lovers.",
      "The combination of fresh tuna, zesty lime juice, and creamy avocado creates a burst of flavors.",
      "Ideal as an appetizer or a light meal, served with crispy crackers or toast.",
    ],
    steps: [
      "Dice the fresh tuna into small cubes.",
      "Finely chop the red onion and dice the avocado.",
      "In a bowl, mix the tuna, red onion, avocado, and lime juice.",
      "Season with salt and pepper to taste.",
      "Chill the mixture in the refrigerator for 20 minutes.",
      "Serve with crispy crackers or toast.",
    ],
  },
  {
    id: "02",
    name: "Grilled Chicken Salad",
    image: require("../assets/images/download (2).jpg"),
    rating: "4.5",
    ingradients: ["Chicken Breast", "Lettuce", "Cherry Tomatoes", "Olive Oil"],
    time: "30 mins",
    difficulty: "Easy",
    calories: "350 cal",
    description: [
      "A healthy and protein-packed salad that’s quick to prepare.",
      "Juicy grilled chicken pairs perfectly with fresh lettuce and sweet cherry tomatoes.",
      "Drizzled with olive oil for a simple yet satisfying meal.",
    ],
    steps: [
      "Season the chicken breast with salt, pepper, and olive oil.",
      "Grill the chicken on medium heat until fully cooked.",
      "Slice the grilled chicken into strips.",
      "Wash and chop the lettuce and cherry tomatoes.",
      "Arrange the lettuce, cherry tomatoes, and chicken in a bowl.",
      "Drizzle with olive oil and serve.",
    ],
  },
  {
    id: "03",
    name: "Pasta Carbonara",
    image: require("../assets/images/download (3).jpg"),
    rating: "4.7",
    ingradients: ["Spaghetti", "Eggs", "Parmesan Cheese", "Bacon"],
    time: "25 mins",
    difficulty: "Medium",
    calories: "520 cal",
    description: [
      "A classic Italian dish that’s creamy, rich, and indulgent.",
      "Made with crispy bacon, Parmesan cheese, and a silky egg-based sauce.",
      "Perfect for a quick dinner that feels gourmet.",
    ],
    steps: [
      "Cook the spaghetti according to package instructions.",
      "Fry the bacon until crispy, then chop into small pieces.",
      "In a bowl, whisk together eggs and grated Parmesan cheese.",
      "Drain the pasta and add it to the pan with the bacon.",
      "Remove from heat and quickly stir in the egg and cheese mixture.",
      "Serve immediately with extra Parmesan on top.",
    ],
  },
  {
    id: "04",
    name: "Beef Steak",
    image: require("../assets/images/download (4).jpg"),
    rating: "4.8",
    ingradients: ["Beef", "Garlic", "Butter", "Rosemary"],
    time: "50 mins",
    difficulty: "Hard",
    calories: "600 cal",
    description: [
      "A hearty and flavorful steak dish that’s perfect for special occasions.",
      "Seared to perfection with garlic, butter, and aromatic rosemary.",
      "Pair it with mashed potatoes or a side of vegetables for a complete meal.",
    ],
    steps: [
      "Season the beef steak generously with salt and pepper.",
      "Heat a pan with butter and add crushed garlic and rosemary.",
      "Sear the steak on high heat for 2-3 minutes on each side.",
      "Reduce the heat and cook to your desired doneness.",
      "Let the steak rest for 5 minutes before slicing.",
      "Serve with mashed potatoes or vegetables.",
    ],
  },
  {
    id: "05",
    name: "Vegan Buddha Bowl",
    image: require("../assets/images/download (5).jpg"),
    rating: "4.6",
    ingradients: ["Quinoa", "Chickpeas", "Avocado", "Spinach"],
    time: "35 mins",
    difficulty: "Easy",
    calories: "400 cal",
    description: [
      "A vibrant and nutritious bowl packed with plant-based goodness.",
      "Quinoa and chickpeas provide protein, while avocado adds creaminess.",
      "Drizzle with your favorite dressing for a wholesome and satisfying meal.",
    ],
    steps: [
      "Cook the quinoa according to package instructions.",
      "Rinse and drain the chickpeas, then season with olive oil and spices.",
      "Slice the avocado and wash the spinach.",
      "Assemble the bowl by layering quinoa, chickpeas, avocado, and spinach.",
      "Drizzle with your favorite dressing.",
      "Serve immediately and enjoy.",
    ],
  },
  {
    id: "06",
    name: "Shrimp Scampi",
    image: require("../assets/images/download (6).jpg"),
    rating: "4.4",
    ingradients: ["Shrimp", "Garlic", "Lemon", "Pasta"],
    time: "30 mins",
    difficulty: "Medium",
    calories: "450 cal",
    description: [
      "A light and flavorful seafood pasta dish that’s quick to make.",
      "Garlic, lemon, and butter create a zesty sauce for succulent shrimp.",
      "Perfect for a weeknight dinner or a fancy meal.",
    ],
    steps: [
      "Cook the pasta according to package instructions.",
      "In a pan, sauté minced garlic in butter until fragrant.",
      "Add the shrimp and cook until pink and opaque.",
      "Squeeze in lemon juice and season with salt and pepper.",
      "Toss the cooked pasta in the shrimp and sauce.",
      "Serve with a sprinkle of parsley and lemon wedges.",
    ],
  },
  {
    id: "07",
    name: "Mushroom Risotto",
    image: require("../assets/images/download (7).jpg"),
    rating: "4.3",
    ingradients: ["Arborio Rice", "Mushrooms", "Parmesan Cheese", "White Wine"],
    time: "45 mins",
    difficulty: "Medium",
    calories: "480 cal",
    description: [
      "A creamy and comforting Italian rice dish that’s full of umami flavors.",
      "Made with earthy mushrooms, Parmesan cheese, and a splash of white wine.",
      "Ideal for a cozy dinner or a special occasion.",
    ],
    steps: [
      "Sauté chopped mushrooms in butter until tender.",
      "Add Arborio rice and toast for 2-3 minutes.",
      "Pour in white wine and stir until absorbed.",
      "Gradually add warm broth, stirring until the rice is creamy.",
      "Stir in grated Parmesan cheese and season with salt and pepper.",
      "Serve hot with extra Parmesan on top.",
    ],
  },
  {
    id: "08",
    name: "Salmon Teriyaki",
    image: require("../assets/images/download (8).jpg"),
    rating: "4.7",
    ingradients: ["Salmon", "Soy Sauce", "Ginger", "Honey"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "430 cal",
    description: [
      "A sweet and savory dish that’s both healthy and delicious.",
      "Salmon is glazed with a homemade teriyaki sauce made from soy sauce, ginger, and honey.",
      "Serve with steamed rice and vegetables for a complete meal.",
    ],
    steps: [
      "Marinate the salmon in soy sauce, ginger, and honey for 15 minutes.",
      "Heat a pan and sear the salmon skin-side down until crispy.",
      "Flip the salmon and cook until done.",
      "Pour the remaining marinade into the pan and reduce to a glaze.",
      "Drizzle the glaze over the salmon.",
      "Serve with steamed rice and vegetables.",
    ],
  },
  {
    id: "09",
    name: "Chocolate Lava Cake",
    image: require("../assets/images/download (9).jpg"),
    rating: "4.9",
    ingradients: ["Dark Chocolate", "Butter", "Eggs", "Flour"],
    time: "30 mins",
    difficulty: "Hard",
    calories: "550 cal",
    description: [
      "A decadent dessert that’s sure to impress your guests.",
      "The cake has a gooey, molten chocolate center that oozes out when cut.",
      "Best served warm with a scoop of vanilla ice cream.",
    ],
    steps: [
      "Melt dark chocolate and butter together.",
      "Whisk eggs and sugar until fluffy, then fold in the chocolate mixture.",
      "Add flour and mix until just combined.",
      "Pour the batter into greased ramekins.",
      "Bake at 375°F (190°C) for 10-12 minutes.",
      "Serve warm with vanilla ice cream.",
    ],
  },
  {
    id: "10",
    name: "Greek Yogurt Parfait",
    image: require("../assets/images/download (10).jpg"),
    rating: "4.5",
    ingradients: ["Greek Yogurt", "Granola", "Honey", "Berries"],
    time: "15 mins",
    difficulty: "Easy",
    calories: "300 cal",
    description: [
      "A quick and healthy breakfast or snack option.",
      "Layered with creamy Greek yogurt, crunchy granola, and fresh berries.",
      "Drizzle with honey for a touch of natural sweetness.",
    ],
    steps: [
      "Layer Greek yogurt at the bottom of a glass.",
      "Add a layer of granola on top of the yogurt.",
      "Add a layer of fresh berries.",
      "Repeat the layers until the glass is full.",
      "Drizzle honey on top.",
      "Serve immediately and enjoy.",
    ],
  },
  {
    id: "11",
    name: "Sweet and Sour Pork",
    image: require("../assets/images/download (11).jpg"),
    rating: "4.5",
    ingradients: ["Pork", "Pineapple", "Bell Peppers", "Soy Sauce"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "520 cal",
    description: [
      "A classic Chinese dish that’s both tangy and sweet.",
      "Tender pork is stir-fried with pineapple, bell peppers, and a flavorful sauce.",
      "Serve with steamed rice for a satisfying meal.",
    ],
    steps: [
      "Marinate the pork in soy sauce and cornstarch for 15 minutes.",
      "Stir-fry the pork until browned, then set aside.",
      "In the same pan, stir-fry pineapple and bell peppers.",
      "Add the pork back to the pan and pour in the sweet and sour sauce.",
      "Cook until the sauce thickens.",
      "Serve with steamed rice.",
    ],
  },
  {
    id: "12",
    name: "Lasagna",
    image: require("../assets/images/download (12).jpg"),
    rating: "4.7",
    ingradients: ["Lasagna Sheets", "Ground Beef", "Tomato Sauce", "Cheese"],
    time: "60 mins",
    difficulty: "Hard",
    calories: "750 cal",
    description: [
      "A hearty and comforting Italian classic that’s perfect for feeding a crowd.",
      "Layered with pasta, rich tomato sauce, ground beef, and melted cheese.",
      "Baked to perfection for a gooey and satisfying dish.",
    ],
    steps: [
      "Cook the lasagna sheets according to package instructions.",
      "Brown the ground beef and mix with tomato sauce.",
      "Layer the lasagna sheets, beef mixture, and cheese in a baking dish.",
      "Repeat the layers until the dish is full.",
      "Top with cheese and bake at 375°F (190°C) for 30 minutes.",
      "Let it cool slightly before serving.",
    ],
  },
  {
    id: "13",
    name: "Butter Chicken",
    image: require("../assets/images/download (13).jpg"),
    rating: "4.8",
    ingradients: ["Chicken", "Tomato Sauce", "Butter", "Cream"],
    time: "50 mins",
    difficulty: "Medium",
    calories: "650 cal",
    description: [
      "A rich and creamy Indian curry that’s full of flavor.",
      "Tender chicken is cooked in a spiced tomato and butter sauce.",
      "Best served with naan or steamed rice.",
    ],
    steps: [
      "Marinate the chicken in yogurt and spices for 30 minutes.",
      "Cook the chicken in a pan until browned, then set aside.",
      "In the same pan, melt butter and add tomato sauce and spices.",
      "Add the chicken back to the pan and simmer in the sauce.",
      "Stir in cream and cook until heated through.",
      "Serve with naan or steamed rice.",
    ],
  },
  {
    id: "14",
    name: "Shepherd's Pie",
    image: require("../assets/images/download (14).jpg"),
    rating: "4.6",
    ingradients: ["Ground Lamb", "Potatoes", "Carrots", "Peas"],
    time: "55 mins",
    difficulty: "Medium",
    calories: "700 cal",
    description: [
      "A comforting and hearty British classic.",
      "Layered with ground lamb, vegetables, and creamy mashed potatoes.",
      "Baked until golden and bubbling for the ultimate comfort food.",
    ],
    steps: [
      "Cook and mash the potatoes with butter and milk.",
      "Brown the ground lamb in a pan with chopped carrots and peas.",
      "Season the lamb mixture with salt, pepper, and herbs.",
      "Layer the lamb mixture in a baking dish and top with mashed potatoes.",
      "Bake at 375°F (190°C) for 20-25 minutes until golden.",
      "Serve hot and enjoy.",
    ],
  },
  {
    id: "15",
    name: "Crème Brûlée",
    image: require("../assets/images/download (15).jpg"),
    rating: "4.9",
    ingradients: ["Heavy Cream", "Egg Yolks", "Sugar", "Vanilla"],
    time: "45 mins",
    difficulty: "Hard",
    calories: "480 cal",
    description: [
      "A luxurious French dessert with a creamy custard base.",
      "Topped with a layer of caramelized sugar that cracks when tapped.",
      "Perfect for a fancy dinner or a special treat.",
    ],
    steps: [
      "Heat heavy cream and vanilla in a saucepan until warm.",
      "Whisk egg yolks and sugar until pale, then slowly add the warm cream.",
      "Strain the mixture and pour into ramekins.",
      "Bake in a water bath at 325°F (160°C) for 40 minutes.",
      "Chill the custards, then sprinkle sugar on top and caramelize with a torch.",
      "Serve chilled.",
    ],
  },
  {
    id: "16",
    name: "Ratatouille",
    image: require("../assets/images/download (16).jpg"),
    rating: "4.5",
    ingradients: ["Zucchini", "Tomatoes", "Bell Peppers", "Eggplant"],
    time: "50 mins",
    difficulty: "Medium",
    calories: "350 cal",
    description: [
      "A colorful and healthy vegetable dish from Provence, France.",
      "Made with zucchini, tomatoes, bell peppers, and eggplant.",
      "Perfect as a side dish or a light main course.",
    ],
    steps: [
      "Slice the zucchini, tomatoes, bell peppers, and eggplant.",
      "Sauté the vegetables in olive oil until tender.",
      "Season with salt, pepper, and herbs.",
      "Layer the vegetables in a baking dish.",
      "Bake at 375°F (190°C) for 20-25 minutes.",
      "Serve warm as a side or main dish.",
    ],
  },
  {
    id: "17",
    name: "Paella",
    image: require("../assets/images/download (17).jpg"),
    rating: "4.6",
    ingradients: ["Rice", "Shrimp", "Chicken", "Saffron"],
    time: "60 mins",
    difficulty: "Hard",
    calories: "700 cal",
    description: [
      "A traditional Spanish rice dish that’s bursting with flavor.",
      "Made with shrimp, chicken, and saffron-infused rice.",
      "Perfect for a festive meal or a family gathering.",
    ],
    steps: [
      "Sauté chicken and shrimp in a large pan until cooked.",
      "Add chopped onions, garlic, and bell peppers.",
      "Stir in rice and saffron, then add chicken broth.",
      "Simmer until the rice is cooked and the liquid is absorbed.",
      "Add peas and cook for an additional 5 minutes.",
      "Serve hot with lemon wedges.",
    ],
  },
  {
    id: "18",
    name: "Egg Fried Rice",
    image: require("../assets/images/download (18).jpg"),
    rating: "4.4",
    ingradients: ["Rice", "Eggs", "Soy Sauce", "Spring Onion"],
    time: "25 mins",
    difficulty: "Easy",
    calories: "400 cal",
    description: [
      "A quick and versatile dish that’s perfect for using up leftover rice.",
      "Scrambled eggs and spring onions add flavor and texture.",
      "Ideal as a side dish or a light meal on its own.",
    ],
    steps: [
      "Heat oil in a pan and scramble the eggs.",
      "Add cooked rice and stir to combine.",
      "Add soy sauce and season with salt and pepper.",
      "Stir in chopped spring onions.",
      "Cook until everything is heated through.",
      "Serve hot as a side or main dish.",
    ],
  },
  {
    id: "19",
    name: "Clam Chowder",
    image: require("../assets/images/download (19).jpg"),
    rating: "4.7",
    ingradients: ["Clams", "Potatoes", "Cream", "Onion"],
    time: "45 mins",
    difficulty: "Medium",
    calories: "500 cal",
    description: [
      "A creamy and comforting soup that’s perfect for chilly days.",
      "Packed with tender clams, potatoes, and onions.",
      "Best served with crusty bread for dipping.",
    ],
    steps: [
      "Sauté onions and potatoes in butter until tender.",
      "Add clams and cook until they open.",
      "Pour in cream and simmer until the soup thickens.",
      "Season with salt, pepper, and herbs.",
      "Serve hot with crusty bread.",
    ],
  },
  {
    id: "20",
    name: "Pad Thai",
    image: require("../assets/images/download (20).jpg"),
    rating: "4.8",
    ingradients: ["Rice Noodles", "Tofu", "Peanuts", "Tamarind"],
    time: "35 mins",
    difficulty: "Medium",
    calories: "550 cal",
    description: [
      "A popular Thai street food dish that’s both sweet and tangy.",
      "Made with rice noodles, tofu, peanuts, and a flavorful tamarind sauce.",
      "Garnished with lime and fresh herbs for a burst of freshness.",
    ],
    steps: [
      "Soak rice noodles in warm water until soft.",
      "Sauté tofu in a pan until golden.",
      "Add the noodles and tamarind sauce to the pan.",
      "Stir in peanuts and cook until heated through.",
      "Garnish with lime wedges and fresh herbs.",
      "Serve hot and enjoy.",
    ],
  },
];

//Data for categories filter

export const categories = [
  {
    id: "01",
    category: "Breakfast",
  },
  {
    id: "02",
    category: "Lunch",
  },
  {
    id: "03",
    category: "Dinner",
  },
  {
    id: "04",
    category: "Asian",
  },
  {
    id: "05",
    category: "Italian",
  },
  {
    id: "06",
    category: "Desserts",
  },
  {
    id: "07",
    category: "Vegeterian",
  },
  {
    id: "08",
    category: "Seafood",
  },
];
