export const colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#fff",
  COLOR_DARK: "#000",
  COLOR_DARK_ALT: "#262626",
};

export const recipeList = [
  {
    id: "01",
    name: "Tuna Tartare",
    image: require("../assets/images/download(1).jpg"),
    rating: "4.2",
    ingradients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "420 cal",
  },
  {
    id: "02",
    name: "Grilled Chicken Salad",
    image: require("../assets/images/download (2).jpg"),
    rating: "4.5",
    ingradients: ["Chicken Breast", "Lettuce", "Cherry Tomatoes", "Olive Oil"],
    time: "30 mins",
    difficulty: "Easy",
    calories: "350 cal",
  },
  {
    id: "03",
    name: "Pasta Carbonara",
    image: require("../assets/images/download (3).jpg"),
    rating: "4.7",
    ingradients: ["Spaghetti", "Eggs", "Parmesan Cheese", "Bacon"],
    time: "25 mins",
    difficulty: "Medium",
    calories: "520 cal",
  },
  {
    id: "04",
    name: "Beef Steak",
    image: require("../assets/images/download (4).jpg"),
    rating: "4.8",
    ingradients: ["Beef", "Garlic", "Butter", "Rosemary"],
    time: "50 mins",
    difficulty: "Hard",
    calories: "600 cal",
  },
  {
    id: "05",
    name: "Vegan Buddha Bowl",
    image: require("../assets/images/download (5).jpg"),
    rating: "4.6",
    ingradients: ["Quinoa", "Chickpeas", "Avocado", "Spinach"],
    time: "35 mins",
    difficulty: "Easy",
    calories: "400 cal",
  },
  {
    id: "06",
    name: "Shrimp Scampi",
    image: require("../assets/images/download (6).jpg"),
    rating: "4.4",
    ingradients: ["Shrimp", "Garlic", "Lemon", "Pasta"],
    time: "30 mins",
    difficulty: "Medium",
    calories: "450 cal",
  },
  {
    id: "07",
    name: "Mushroom Risotto",
    image: require("../assets/images/download (7).jpg"),
    rating: "4.3",
    ingradients: ["Arborio Rice", "Mushrooms", "Parmesan Cheese", "White Wine"],
    time: "45 mins",
    difficulty: "Medium",
    calories: "480 cal",
  },
  {
    id: "08",
    name: "Salmon Teriyaki",
    image: require("../assets/images/download (8).jpg"),
    rating: "4.7",
    ingradients: ["Salmon", "Soy Sauce", "Ginger", "Honey"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "430 cal",
  },
  {
    id: "09",
    name: "Chocolate Lava Cake",
    image: require("../assets/images/download (9).jpg"),
    rating: "4.9",
    ingradients: ["Dark Chocolate", "Butter", "Eggs", "Flour"],
    time: "30 mins",
    difficulty: "Hard",
    calories: "550 cal",
  },
  {
    id: "10",
    name: "Greek Yogurt Parfait",
    image: require("../assets/images/download (10).jpg"),
    rating: "4.5",
    ingradients: ["Greek Yogurt", "Granola", "Honey", "Berries"],
    time: "15 mins",
    difficulty: "Easy",
    calories: "300 cal",
  },
  {
    id: "11",
    name: "Sweet and Sour Pork",
    image: require("../assets/images/download (11).jpg"),
    rating: "4.5",
    ingradients: ["Pork", "Pineapple", "Bell Peppers", "Soy Sauce"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "520 cal",
  },
  {
    id: "12",
    name: "Lasagna",
    image: require("../assets/images/download (12).jpg"),
    rating: "4.7",
    ingradients: ["Lasagna Sheets", "Ground Beef", "Tomato Sauce", "Cheese"],
    time: "60 mins",
    difficulty: "Hard",
    calories: "750 cal",
  },
  {
    id: "13",
    name: "Butter Chicken",
    image: require("../assets/images/download (13).jpg"),
    rating: "4.8",
    ingradients: ["Chicken", "Tomato Sauce", "Butter", "Cream"],
    time: "50 mins",
    difficulty: "Medium",
    calories: "650 cal",
  },
  {
    id: "14",
    name: "Shepherd's Pie",
    image: require("../assets/images/download (14).jpg"),
    rating: "4.6",
    ingradients: ["Ground Lamb", "Potatoes", "Carrots", "Peas"],
    time: "55 mins",
    difficulty: "Medium",
    calories: "700 cal",
  },
  {
    id: "15",
    name: "Crème Brûlée",
    image: require("../assets/images/download (15).jpg"),
    rating: "4.9",
    ingradients: ["Heavy Cream", "Egg Yolks", "Sugar", "Vanilla"],
    time: "45 mins",
    difficulty: "Hard",
    calories: "480 cal",
  },
  {
    id: "16",
    name: "Ratatouille",
    image: require("../assets/images/download (16).jpg"),
    rating: "4.5",
    ingradients: ["Zucchini", "Tomatoes", "Bell Peppers", "Eggplant"],
    time: "50 mins",
    difficulty: "Medium",
    calories: "350 cal",
  },
  {
    id: "17",
    name: "Paella",
    image: require("../assets/images/download (17).jpg"),
    rating: "4.6",
    ingradients: ["Rice", "Shrimp", "Chicken", "Saffron"],
    time: "60 mins",
    difficulty: "Hard",
    calories: "700 cal",
  },
  {
    id: "18",
    name: "Egg Fried Rice",
    image: require("../assets/images/download (18).jpg"),
    rating: "4.4",
    ingradients: ["Rice", "Eggs", "Soy Sauce", "Spring Onion"],
    time: "25 mins",
    difficulty: "Easy",
    calories: "400 cal",
  },
  {
    id: "19",
    name: "Clam Chowder",
    image: require("../assets/images/download (19).jpg"),
    rating: "4.7",
    ingradients: ["Clams", "Potatoes", "Cream", "Onion"],
    time: "45 mins",
    difficulty: "Medium",
    calories: "500 cal",
  },
  {
    id: "20",
    name: "Pad Thai",
    image: require("../assets/images/download (20).jpg"),
    rating: "4.8",
    ingradients: ["Rice Noodles", "Tofu", "Peanuts", "Tamarind"],
    time: "35 mins",
    difficulty: "Medium",
    calories: "550 cal",
  }
];

//Data for categories filter

export const categories = [
  {
    id: "01",
    category: "Breakfast",
  },
  {
    id: "02",
    category: "Lunch",
  },
  {
    id: "03",
    category: "Dinner",
  },
  {
    id: "04",
    category: "Asian",
  },
  {
    id: "05",
    category: "Italian",
  },
  {
    id: "06",
    category: "Desserts",
  },
  {
    id: "07",
    category: "Vegeterian",
  },
  {
    id: "08",
    category: "Seafood",
  },
];
